### ISSUE TITLE
Access Denied error : secret must be a stirng or buffer error 

### ISSUE THREAD

**Issue by balakrir** [ashishdasnurkar/update-profile-website#4]
After completing all steps and enabling the rules. we are seeing below error.

Access Denied error : secret must be a string or buffer error 

I think this error is due to JWT secret key but not sure where to update and get the values for that.

thanks,
Bala

**Comment by ashishdasnurkar** [comment]
The error is most likely due to `TOKEN_SECRET` not being set as a environment variable. In the README section, there is some guidance on how to set that with HEROKU command line but if you are hosting your update profile website somewhere else you will need to set that using that platform/OS specific method. This value can be anything but do generate a long random value using some open source tool like openssl for eg. `openssl rand -base64 20`

**Comment by balakrir** [comment]
thanks @ashishdasnurkar!! This works!!
